import os
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.path.join(os.path.dirname(__file__), "data", "jobs.db")

# Security
API_KEY = os.getenv("API_KEY", "dev_secret_key_123")

# Discord Webhook
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL", "")

AGENCY_CONTEXT = {
    "ascend": {
        "name": "Ascend Growth Studio",
        "focus": "D2C & Growth Marketing",
        "strengths": "Paid social (FB/TikTok), ROAS optimization, e-commerce scaling, creative testing framework.",
        "pitch_angle": "We don't just run ads; we install a growth OS to scale from $1M to $10M.",
        "target_roles": [
            "CMO",
            "VP Marketing",
            "Head of Growth",
            "E-commerce Manager",
            "Founder",
        ],
        "industries": [
            "E-commerce",
            "DTC Brands",
            "Health & Wellness",
            "Consumer Goods",
            "Fashion",
        ],
        "sample_services": [
            "Facebook/TikTok Ads Management",
            "ROAS Optimization",
            "Creative Testing",
            "Email Marketing (Klaviyo)",
            "Landing Page Optimization",
        ],
    },
    "apex": {
        "name": "Apex Partners",
        "focus": "Fractional C-Suite & Strategy",
        "strengths": "Executive leadership, strategic planning, board advisory, operational efficiency.",
        "pitch_angle": "Senior-level strategic guidance without the full-time C-suite cost.",
        "target_roles": [
            "CEO",
            "CFO",
            "COO",
            "Board Member",
            "Operating Partner",
            "VP Finance",
        ],
        "industries": [
            "Private Equity Portfolio",
            "SaaS",
            "Manufacturing",
            "Professional Services",
        ],
        "sample_services": [
            "Fractional CFO/COO",
            "Strategic Planning",
            "M&A Due Diligence",
            "Operational Efficiency",
            "Financial Modeling",
        ],
    },
    "socketlogic": {
        "name": "SocketLogic Labs",
        "focus": "Technical Automation & Engineering",
        "strengths": "Complex API integrations, Python/JS, AI agents, backend infrastructure.",
        "pitch_angle": "We build the automation backbone that lets you scale without headcount.",
        "target_roles": [
            "CTO",
            "VP Engineering",
            "Head of Ops",
            "IT Director",
            "Founder",
        ],
        "industries": ["SaaS", "Fintech", "Healthcare Tech", "Logistics", "E-commerce"],
        "sample_services": [
            "Custom API Integrations",
            "Process Automation (Zapier/Make)",
            "Backend Development",
            "AI Chatbots & Agents",
            "Data Pipelines",
        ],
    },
    "theshield": {
        "name": "The Shield",
        "focus": "Legal & Compliance",
        "strengths": "Legal documentation, compliance frameworks, privacy policies, HR policies.",
        "pitch_angle": "Protecting your business with bulletproof legal foundations.",
        "target_roles": [
            "CEO",
            "COO",
            "Head of Legal",
            "Compliance Manager",
            "HR Director",
        ],
        "industries": [
            "SaaS",
            "E-commerce",
            "Fintech",
            "Marketing Agencies",
            "Startups",
        ],
        "sample_services": [
            "Terms of Service",
            "Privacy Policies (GDPR)",
            "Employee Handbooks",
            "Compliance Audits",
            "Contract Templates",
        ],
    },
    "infrastructure": {
        "name": "SecurOps Solution",
        "focus": "Cybersecurity & IT Infrastructure",
        "strengths": "SOC operations, severe hardening, network design, 24/7 monitoring, disaster recovery.",
        "pitch_angle": "Enterprise-grade security and infrastructure stability for growing businesses.",
        "target_roles": [
            "CTO",
            "CISO",
            "IT Manager",
            "VP Infrastructure",
            "System Administrator",
        ],
        "industries": [
            "Fintech",
            "Healthcare",
            "SaaS",
            "Enterprise",
            "Managed Services",
        ],
        "sample_services": [
            "SOC & Threat Monitoring",
            "Network Design & Optimization",
            "Server Hardening",
            "IT Helpdesk & Support",
            "Disaster Recovery Planning",
        ],
    },
}

# Classification Keywords (for AI fallback and pre-filtering)
AGENCY_KEYWORDS = {
    "ascend": [
        "marketing",
        "growth",
        "ads",
        "seo",
        "paid media",
        "ppc",
        "facebook ads",
        "tiktok ads",
        "google ads",
        "shopify",
        "d2c",
        "direct to consumer",
        "ecommerce",
        "e-commerce",
        "klaviyo",
        "funnel",
        "landing page",
        "brand",
        "copywriting",
        "email marketing",
        "social media",
        "influencer",
        "ugc",
        "creative",
        "gohighlevel",
        "lead generation",
        "cold email",
        "content marketing",
    ],
    "apex": [
        "executive",
        "c-suite",
        "fractional",
        "interim",
        "ceo",
        "cfo",
        "coo",
        "cmo",
        "chief",
        "vp",
        "vice president",
        "director",
        "board",
        "advisor",
        "strategy",
        "strategic planning",
        "operations",
        "operational",
        "finance",
        "financial",
        "p&l",
        "budgeting",
        "forecast",
        "estimations",
        "due diligence",
        "m&a",
        "private equity",
        "portfolio",
        "scaling",
        "founder",
        "consultant",
    ],
    "socketlogic": [
        "python",
        "javascript",
        "api",
        "backend",
        "automation",
        "integration",
        "workflow",
        "scripting",
        "developer",
        "engineer",
        "devops",
        "cloud",
        "aws",
        "gcp",
        "saas",
        "software",
        "microservices",
        "zapier",
        "make",
        "n8n",
        "chatbot",
        "llm",
        "ai",
        "machine learning",
        "data",
        "scraping",
        "database",
        "sql",
        "mongodb",
        "tech",
        "agento",
        "webhooks",
    ],
    "theshield": [
        "legal",
        "compliance",
        "gdpr",
        "privacy policy",
        "terms of service",
        "contracts",
        "nda",
        "hr",
        "human resources",
        "employee handbook",
        "regulatory",
        "audit",
        "risk management",
    ],
}

# Jobs matching these keywords should be REJECTED (not shown)
REJECT_KEYWORDS = [
    "babysitter",
    "nanny",
    "childcare",
    "personal assistant",
    "data entry",
    "virtual assistant",
    "transcription",
    "typing",
    "customer service representative",
    "looking for someone cheap",
    "intern",
    "unpaid",
    "volunteer",
]
